name: mop
url: http://skyaspnet.github.io/
source:      .
destination: ./_site
plugins_dir:     ./_plugins
lsi:      false
safe:     false
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /blog/:year/:month/:title
paginate: 12
paginate_path: "articles/page:num"
encoding: utf-8

post_defaults:
  layout: post

redcarpet:
  extensions: ["tables", "autolink"]
  
# Gems
gems: [jekyll-paginate]